SAMPLES: [
          "Col-0_bud-1",
          "Col-0_bud-2",
          "Col-0_bud-3",
          "arp6_bud-1",
          "arp6_bud-2",
          "arp6_bud-3",
          "pie1_bud-1",
          "pie1_bud-2",
          "pie1_bud-3"
         ]
THREADS: 35
MEMORY: "250g"
FILTER:
  fastqc:
      adapters: "data/adapter_list.txt"
  cutadapt:
      adapter: CTGTCTCTTATACACATCT # Sequence for trimming Nextera library reads 
      quality-filter: 19 # -q
      minimum-overlap: 3 # -O (default: 3)
      extra-params:
# NOTE: reference genome-specific mapping parameters
MAPPING:
      reference: "/home/nison/work/refgenome/TAIR10/bowtie2_index/tair10"
      MAPQmaxi: 10 # -q
      sortMemory: "5G"
COVERAGE:
      normalizeUsing: "BPM"
      ignoreForNormalization: "mitochondria chloroplast" # Reference genome-specific parameter
      extendReads: 150
      binSize: 1
      genomeBinSize: 10000
      genomeBinName: "10kb"

# NEBNext adapter and universal primer for Illumina:
# https://international.neb.com/-/media/catalog/datacards-or-manuals/manuale7335.pdf
# https://www.biostars.org/p/149301/
# https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq
# http://bioinformatics.cvr.ac.uk/blog/illumina-adapter-and-primer-sequences/
# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
